changesetBaseRefs:
  - main
  - origin/main

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@storybook/core@*":
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
