// This file was generated by lezer-generator. You probably shouldn't edit it.
export const eof = 26,
  Template = 1,
  Content = 2,
  LiquidTag = 3,
  Identifier = 7,
  PropertyAccessor = 8,
  IndexAccessor = 9,
  Number = 10,
  LiquidFilter = 12,
  LiquidObject = 17,
  Text = 20;
