// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  eof = 31,
  Template = 1,
  Content = 2,
  LiquidTag = 3,
  ParenthesizedExpression = 7,
  LiquidFilter = 9,
  Identifier = 12,
  PropertyAccessor = 15,
  IndexAccessor = 16,
  Number = 18,
  LiquidObject = 22,
  Text = 25
